using System.Xml.Linq;

namespace Payroll.Core;

/// <summary>Builds the VAT3 XML file for manual upload to ROS. Field names/attribute order match a real
/// file previously generated by BulletHQ for the same company, byte-for-byte in structure.</summary>
public static class Vat3XmlWriter
{
    public static string Build(VatReturn vatReturn)
    {
        var element = new XElement("VAT3",
            new XAttribute("name", vatReturn.CompanyName),
            new XAttribute("regnum", vatReturn.VatRegistrationNumber),
            new XAttribute("startdate", vatReturn.Period.Start.ToString("dd/MM/yyyy")),
            new XAttribute("enddate", vatReturn.Period.End.ToString("dd/MM/yyyy")),
            new XAttribute("sales", vatReturn.RoundedSalesVat),
            new XAttribute("purchs", vatReturn.RoundedPurchasesVat),
            new XAttribute("goodsto", 0),
            new XAttribute("goodsfrom", 0),
            new XAttribute("servicesto", 0),
            new XAttribute("servicesfrom", 0),
            new XAttribute("postponedAccounting", 0),
            new XAttribute("currency", "E"),
            new XAttribute("type", 0),
            new XAttribute("filefreq", 0),
            new XAttribute("formversion", 1),
            new XAttribute("language", "E"));

        var declaration = new XDeclaration("1.0", "UTF-8", null);
        return $"{declaration} {element.ToString(SaveOptions.DisableFormatting)}";
    }
}
